### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by BillyYiuCimda** [svhoy/uwb_zephyr_dwm3001cdk#26]
Having this error in the build process: sit/lib/sit/sit.c:359: undefined reference to `dwt_read32bitreg'. Anything I missed out?

**Comment by svhoy** [comment]
Sorry for the late Response, please just comment out the line 359, 360 and 361. They are not neassery for the functionalty of the code. 

I will remove this because dwt_read32bitreg ist not longer in the API binarys from Qrovo

**Comment by svhoy** [comment]
should be fixed with commit fc87c67
