### ISSUE TITLE
Failed to initialise dwt

### ISSUE THREAD

**Issue by pascal-kuschkowitz** [svhoy/uwb_zephyr_dwm3001cdk#27]
I am trying to run the function `dwt_getpartid`.
Therefore, I try to initialize using `dwt_initialise(0)`. That leaves me with a **BUS FAULT**.
Looking at your sit code, I then tried running the `device_init`, etc. from `sit.c` ll. 632ff., however without any success.

Btw. I am using jlink instead of nrfjprog.

**Comment by svhoy** [comment]
Hi, 

sorry for the late response. 

I tried with the following code: 

```	
        if (dwt_initialise(DWT_READ_OTP_PID) == DWT_ERROR) {
		LOG_ERR("dwt_initialise failed");
		return -1;
	}
	/* Enabling LEDs here for debug so that for each TX the D1 LED will flash on DW3000 red eval-shield boards. */
	dwt_setleds(DWT_LEDS_ENABLE | DWT_LEDS_INIT_BLINK);
	uint32_t device_id = dwt_getpartid();
	LOG_INF("DW3000 initialized %" PRIu32 "!", device_id);
	/* if the dwt_configure returns DWT_ERROR either the PLL or RX calibration has failed the host should reset the device */
	if (dwt_configure(&sit_device_config)){
		LOG_ERR("dwt_configure failed");
		return -2;
	}
```

and got an Number that should be the Part ID. 

The function device_init() just initialze the SPI connection. 

Initialize the DW chip with dwt_initialise(DWT_READ_OTP_PID) to read the Part ID. Then you can read it with getpartid. (See  DW3xxx DEVICE DRIVER APPLICATION PROGRAMMING INTERFACE (API) GUIDE Page 27)
